version: '3.7'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - develop
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq:management-alpine
    networks:
      - develop
    ports:
      - 15672:15672

networks:
  develop:
    name: develop