version: "3.7"

services:
  rmq-kafka-worker:
    build: .
    command: python /app/app/main.py
    environment:
      LOG_LEVEL: DEBUG
      RMQ_HOST: rabbitmq
      RMQ_USER: guest
      RMQ_PASS: guest
      RMQ_PORT: 5672
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    networks:
      - develop

networks:
  develop:
    external: true